[general]
import = [
    "~/.config/alacritty/themes/camila.toml"
]

[window]
padding = { x = 0, y = 0 }
opacity = 1.0
blur = false



[font]
size = 15.0
# normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
# normal = { family = "Iosevka Nerd Font Propo", style = "Regular" }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Control"
# action = "Copy"
